server {
    listen 80;
    listen [::]:80;
    server_name llk.ichenj.com;

    location ^~ /.well-known/acme-challenge/ {
        root /opt/wire-pairs/acme;
        default_type text/plain;
    }

    location / {
        return 503;
    }
}
